[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "014ab39c2ca5eda230288bd54fe603d13ae263ee"
os = "windows"

    [[HelloWorldC.download]]
    sha256 = "6caacb299257f34b6a1239ac7f74486509a0e574cc2523bfb189da629138db29"
    url = "https://github.com/barche/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.4+0/HelloWorldC.v1.2.4.x86_64-w64-mingw32.tar.gz"
